### ISSUE TITLE
Maybe add Bones as an option?

### ISSUE THREAD

**Issue by Ewanophobia** [boatbomber/GridCreator#2]
Recently I've been using this module for fluid simulation and I haven't found an option which is particularly great for large areas of fluids. iirc bones are super optimised so many add them as a DrawType?

If you can't do this I'll have a go at doing this myself and submitting a PR in the future (if I ever get round to doing it haha)

**Comment by boatbomber** [comment]
I made this system before bones were publicly available, iirc. I'd love to see a PR for it in the future, as it's something I've wanted to support but haven't the time to create myself.

**Comment by Ewanophobia** [comment]
Unfortunately this is impossible, you have to import your own grid from Blender instead of making a grid and placing bones down.

Until Roblox adds some functionality with bones being able to be used on parts and such, this is currently impossible.
